name: Lint
on: [pull_request]

env:
  PYTHON_VERSION: "3.12.1"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install poetry using pipx
        run: |
          pipx install poetry
          pipx ensurepath

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12.1"
          cache: "poetry"

      - name: Install dependencies
        run: |
          poetry config virtualenvs.in-project true
          poetry install --no-interaction --no-root --only linting

      - name: Lint Python files with ruff
        run: poetry run ruff --show-source .
